version: '3.7'

services:
    db:
        image: "postgres:11"
        environment:
          - "POSTGRES_HOST_AUTH_METHOD=trust"
        volumes:
          - postgres_data:/var/lib/postgresql/data/
    web:
        restart: always
        build: .
        command: poetry run python /code/manage.py runserver 0.0.0.0:8000
        volumes:
        - .:/code
        ports:
        - 8000:8000
        env_file:
        - ./.env.dev

volumes:
  postgres_data: