version: '3.7'

services:
    db:
        image: "postgres:11"
        environment:
          - "POSTGRES_HOST_AUTH_METHOD=trust"
        volumes:
          - postgres_data:/var/lib/postgresql/data/
    web:
        restart: always
        build: .
        command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - .:/code/staticfiles
        expose:
            - 8000
        env_file:
            - ./.env.dev
        depends_on: 
            - db
    nginx:
        build: ./nginx
        volumes: 
            - static_volume:/code/staticfiles
        ports: 
            - 1337:80
        depends_on: 
            - web


volumes:
    postgres_data:
    static_volume: