name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose -f docker-compose.yml build
    - name: Docker compose run
      run: docker-compose -f docker-compose.yml up
